//! Windows x86_64 release builds currently ship a host-target-focused LLVM package.
//! Inkwell's target helpers pull in references to many optional target init symbols
//! from the same object file even though Draton only initializes the native target.
//! Provide no-op stubs for the absent targets so packaged Windows releases can link.

macro_rules! define_missing_target_stubs {
    ($($name:ident),+ $(,)?) => {
        $(
            #[no_mangle]
            pub unsafe extern "C" fn $name() {}
        )+
    };
}

define_missing_target_stubs!(
    LLVMInitializeAArch64AsmParser,
    LLVMInitializeAArch64AsmPrinter,
    LLVMInitializeAArch64Disassembler,
    LLVMInitializeAArch64Target,
    LLVMInitializeAArch64TargetInfo,
    LLVMInitializeAArch64TargetMC,
    LLVMInitializeARMAsmParser,
    LLVMInitializeARMAsmPrinter,
    LLVMInitializeARMDisassembler,
    LLVMInitializeARMTarget,
    LLVMInitializeARMTargetInfo,
    LLVMInitializeARMTargetMC,
    LLVMInitializeBPFAsmPrinter,
    LLVMInitializeBPFDisassembler,
    LLVMInitializeBPFTarget,
    LLVMInitializeBPFTargetInfo,
    LLVMInitializeBPFTargetMC,
    LLVMInitializeHexagonAsmPrinter,
    LLVMInitializeHexagonDisassembler,
    LLVMInitializeHexagonTarget,
    LLVMInitializeHexagonTargetInfo,
    LLVMInitializeHexagonTargetMC,
    LLVMInitializeLanaiAsmParser,
    LLVMInitializeLanaiAsmPrinter,
    LLVMInitializeLanaiDisassembler,
    LLVMInitializeLanaiTarget,
    LLVMInitializeLanaiTargetInfo,
    LLVMInitializeLanaiTargetMC,
    LLVMInitializeMSP430AsmPrinter,
    LLVMInitializeMSP430Target,
    LLVMInitializeMSP430TargetInfo,
    LLVMInitializeMSP430TargetMC,
    LLVMInitializeMipsAsmParser,
    LLVMInitializeMipsAsmPrinter,
    LLVMInitializeMipsDisassembler,
    LLVMInitializeMipsTarget,
    LLVMInitializeMipsTargetInfo,
    LLVMInitializeMipsTargetMC,
    LLVMInitializePowerPCAsmParser,
    LLVMInitializePowerPCAsmPrinter,
    LLVMInitializePowerPCDisassembler,
    LLVMInitializePowerPCTarget,
    LLVMInitializePowerPCTargetInfo,
    LLVMInitializePowerPCTargetMC,
    LLVMInitializeRISCVAsmParser,
    LLVMInitializeRISCVAsmPrinter,
    LLVMInitializeRISCVDisassembler,
    LLVMInitializeRISCVTarget,
    LLVMInitializeRISCVTargetInfo,
    LLVMInitializeRISCVTargetMC,
    LLVMInitializeSparcAsmParser,
    LLVMInitializeSparcAsmPrinter,
    LLVMInitializeSparcDisassembler,
    LLVMInitializeSparcTarget,
    LLVMInitializeSparcTargetInfo,
    LLVMInitializeSparcTargetMC,
    LLVMInitializeSystemZAsmParser,
    LLVMInitializeSystemZAsmPrinter,
    LLVMInitializeSystemZDisassembler,
    LLVMInitializeSystemZTarget,
    LLVMInitializeSystemZTargetInfo,
    LLVMInitializeSystemZTargetMC,
    LLVMInitializeWebAssemblyAsmParser,
    LLVMInitializeWebAssemblyAsmPrinter,
    LLVMInitializeWebAssemblyDisassembler,
    LLVMInitializeWebAssemblyTarget,
    LLVMInitializeWebAssemblyTargetInfo,
    LLVMInitializeWebAssemblyTargetMC,
    LLVMInitializeXCoreAsmPrinter,
    LLVMInitializeXCoreDisassembler,
    LLVMInitializeXCoreTarget,
    LLVMInitializeXCoreTargetInfo,
    LLVMInitializeXCoreTargetMC,
);
